services:
  rust-template:
    # Nombre del servicio
    image: rust-template # Nombre de la imagen de Docker
    container_name: rust-template # Nombre del contenedor
    build:
      context: ..
      dockerfile: docker/Dockerfile
      target: dev
    volumes:
      - ..:/app # Sincroniza el código fuente con el contenedor
    command: cargo watch -x run # Recarga la app automáticamente
    ports:
      - "8080:8080"
    environment:
      - ENV=development
      - DATABASE_URL=postgres://user:password@db:5432/dbname
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: rust-template-db # Nombre del contenedor de la base de datos
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
